---
# tasks file for ./roles/nginx
- name: Install nginx
  ansible.builtin.apt:
    name: nginx 
    update_cache: yes 
    state: latest

- name: Create folder
  ansible.builtin.file:
    path: /data
    state: directory
    mode: '0755'
    owner: "www-data"
    group: "www-data"
    recurse: true

- name: Copy default
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: 0644

- name: Copy index.html
  ansible.builtin.template:
    src: index.html.j2
    dest: /data/index.html
    owner: "www-data"
    group: "www-data"
    mode: 0644

- name: Restart service nginx
  ansible.builtin.sysvinit:
    name: nginx
    state: restarted