- name: Waiting connection
  hosts: all 
  become: yes
  gather_facts: no
  tasks:
    - name: Waiting connections
      ansible.builtin.wait_for_connection:
    - name: Get facts
      ansible.builtin.setup:

- name: Install extra apps and add users
  hosts: all
  become: yes
  gather_facts: no
  vars_files: 
    - vars.yml
  roles:
    - extra_apps_install
    - users_groups
    - ohmyzsh
    - ssh
    - nginx
    - download_statics
