---
- name: Install oh-my-zsh for users
  tags:
    - skip_ansible_lint
  become: true
  become_user: '{{ item.name_user }}'
  ansible.builtin.shell: |
    if [ ! -d ~/.oh-my-zsh ]; then
    export PATH=$HOME/bin:/usr/local/bin:$PATH && sh -c "$(wget --no-check-certificate https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)" <<EOF
    y
    EOF
    fi
  with_items: "{{ users_list }}"
  when: 
    - item.state == "present"
    - item.shell == "zsh"
  
